---
title: "Justin Moran's CV"
author: Justin Moran
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['datadrivencv/dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

source("datadrivencv/CV_printing_functions.R")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1Kd-qv6oxFzKKzvim2TdFYXslB398zdJ6tKX1Dur064M",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _your-website.com/cv/_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](justin_moran_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV |> print_contact_info()
```

Technical Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV |> print_skill_bars()
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with [**datadrivencv**](https://nickstrayer.me/datadrivencv). 

The source code is available on [GitHub](https://github.com/kyaneos/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Justin Moran {#title}
--------------------------------------------------------------------------------

```{r}
# Note the assignment back to CV. This is so the link stripping works properly in PDF mode
CV <- print_text_block(CV, "intro") 
```

Currently {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV <- CV |> print_section('currently')
```

Education and Training {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- CV |> print_section('education')
```

Manuscripts {data-icon=book}
--------------------------------------------------------------------------------

**Moran, J.**, Jolly, E. (in prep). Transmission and Transformation of Social Reputations in Serial Reproduction.

Open Scientific Software {data-icon=code}
--------------------------------------------------------------------------------

::: aside
```{r}
if(params$pdf_mode){
  cat("Software projects focused on research tools and educational applications, demonstrating commitment to open science and reproducible research.")
} else {
  cat("Software projects focused on research tools and educational applications, demonstrating commitment to open science and reproducible research.")
}
```
:::

```{r}
CV <- CV |> print_section('software')
```

```{r}
print_links(CV)
```